[package]
name = "studio-sources"
version.workspace = true
edition.workspace = true
publish.workspace = true
[dependencies]
flate2.workspace = true
base64.workspace = true
studio-domain = { path = "../studio-domain" }
studio-application = { path = "../studio-application" }
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
image.workspace = true
libloading.workspace = true
tracing.workspace = true
tempfile.workspace = true
dunce = "1.0.5"
chrono = { version = "0.4", default-features = false, features = ["std"] }
[dev-dependencies]
tracing-subscriber.workspace = true
